---
- name: Download Apache Maven 
  get_url: 
    url: "{{ src_url }}"
    dest: "{{ dest_path }}"

- name: Extract Apache Maven archive
  unarchive:
    src: "{{ maven_archive_dest }}"
    dest: /opt
    remote_src: yes

- name: Update path for maven use
  shell: export PATH={{dest_url}}/bin:$PATH

