---
#Create 'tomcat' group
- name: Add tomcat group
  group:
    name: tomcat

#Create 'tomcat' user and add to 'tomcat' group
- name: Add "tomcat" user
  user:
    name: tomcat
    group: tomcat
    home: /opt

#Check if 'tomcat' folder exists
- name: Check tomcat directory existence
  stat: path=/opt/tomcat
  register: tomcat_dir

#Download tomcat
- name: Download Tomcat
  get_url:
    url: "{{ tomcat_archive_url }}"
    dest: /opt
  when: not tomcat_dir.stat.exists

#Extracts Tomcat
- name: Extract tomcat archive
  unarchive:
    src: "{{ tomcat_archive_dest }}"
    dest: /opt
    owner: tomcat
    group: tomcat
    remote_src: yes
    mode: 777
  when: not tomcat_dir.stat.exists

#Rename folder to 'tomcat'
- name: Rename tomcat folder
  shell: mv /opt/apache-tomcat-10.0.0 /opt/tomcat
  when: not tomcat_dir.stat.exists

#Removes the tar files
- name: Clean up tar files
  file:
    path: "{{ tomcat_archive_dest }}"
    state: absent

#Changes ownership to user 'tomcat'
- name: Change ownership of Tomcat installation
  file: path=/opt/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

#Stopping tomcat
- name: Stop tomcat
  shell: nohup sh /opt/tomcat/bin/shutdown.sh &
  become: true
#  become_user: tomcat

#Copying tomcat config files
- name: copy config files
  template:
    src: server.xml.j2
    dest: /opt/tomcat/conf/server.xml 

#Starting tomcat
- name: Start and enable tomcat
  shell: nohup sh /opt/tomcat/bin/startup.sh &
  become: true

